### PR TITLE
Use Environment Variables to configure project

### PR DESCRIPTION
**Pull request by chrismlusk**
Per #18, this adds the `dotenv` package to the project and uses environment variables an initial attempt to centralize some of the configuration settings.

Primarily, this affects the Gulp build process right now. Instead of changing config values in that directory, we would open the `.env` file, make settings, and run Gulp.

I do like the idea of environment variables as a way to also configure some of the custom javascript. For example, we could add one that triggers different JavaScript modules to be included in the skin. Something like:

```bash
# Valid options: "simple", "dropdown", "megamenu"
PRIMARY_NAV_TYPE = "megamenu"
```

### CODE REVIEW

**Comment by chrismlusk** [comment]
@Accuraty, when you have time, take a look. The two that are worth reviewing are [`.env`](https://github.com/chrismlusk/accuraty-templates/pull/44/files#diff-ff721de0b83cf1a6b31aa584ca2c9d28) and [`project.js`](https://github.com/chrismlusk/accuraty-templates/pull/44/files#diff-1fcdf241432e8b24a9445b5113b7927f). No rush, though.

**Comment by Accuraty** [comment]
Everything looks great to me. So does this change the instructions at initial project setup/deploy so that you would edit .env first? If yes, there are a lot more opportunities... not that I have a good example at the moment.

**Comment by chrismlusk** [comment]
@Accuraty, this would update [step 3](https://github.com/chrismlusk/accuraty-templates#3-set-the-project-name) in the "Getting Started" instructions. Instead of opening `package.json`, you would open `.env` and modify that file. Everything else would stay the same.

When you think of other examples for putting this to use, let me know.

**Comment by chrismlusk** [comment]
Closes #18

**Pull request merged**
