### PR TITLE
Feature/mega menu

### PR DESCRIPTION
**Pull request by chrismlusk**
Adds a DDR Mega Menu template with styles and scripts. (First attempt at #15.)

- Shows three levels of nodes: root, child, grandchild.
- Used alongside Bootstrap's `.navbar-nav` and related classes for the top-level menu.
- Custom classes for the dropdown menus.
- Each second-level menu is a column in the mega dropdown.
- This template renders the Tab icon above each column.
  - If no icon, it renders a placeholder image (for now).
- Each third-level menu is a list of links.
  - If no list of links, it renders the Tab description.

### CODE REVIEW

**Comment by chrismlusk** [comment]
**@Accuraty, please do not merge this. Review only.**

I'm opening this PR so you can check out the Razor/DDR implementation and offer feedback. Surely I've done something wrong or you can suggest improvements. This is the code I've added to get the PDEG mega menu working, so you can see it live at http://pdeg.accuraty.ws.

There are some style issues I'm aware of, but what do you think about this being a starting point for mega menus?

**Comment by Accuraty** [comment]
> what do you think about this being a starting point for mega menus?

Seems perfect to me and looks easy to style. Only BIG question is how will it operate when on mobile?

**Comment by chrismlusk** [comment]
Ok cool. I haven't gotten to mobile yet. I figure it'll just collapse into a normal, multi-level menu that you tap to expand each section/sub-section. Thoughts, @Accuraty?

**Comment by chrismlusk** [comment]
After more learning from ongoing development with [PDEG](https://github.com/Accuraty/PDEG), I think it will be easiest to lean more heavily on Bootstrap's `.dropdown` and `.dropdown-menu` components. Specifically, our mega menus need to be activated by click (not hover), so if we use these dropdown classes in our component, we will inherit all of the functionality from Bootstrap (instead of writing it ourselves).

**Pull request merged**
